name: Main

on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: npm i backend
        run: |
          cd back-end
          npm install

      # Runs a set of commands using the runners shell
      - name: Build frontend
        run: |
          cd front-end
          echo "This contains some access to git repos over non-standard ports"
          rm package-lock.json
          npm install
          npm run build
      
      - name: Package result
        run: |
          mkdir result/
          mkdir result/front-end/
          cp -r front-end/dist result/front-end/dist
          cp -r back-end result/back-end
          tar -czf result.tar.gz result

      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: result.tar.gz
 
  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Test
        run: echo Hello world!
        
      - name: Download Result
        uses: actions/download-artifact@v2.0.10
        with:
          # Artifact name
          name: result
          # Destination path
          path: ./
      
      - name: Extract result
        run: tar -xzf result.tar.gz
        
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
        
      - name: Deploy to EC2
        run: rsync ./result ec2-user@ec2-54-241-152-84.us-west-1.compute.amazonaws.com:. --recursive
